---
- hosts: master-node
  become: true

  tasks:

  - name: docker-bench-security
    command: ./docker-bench-security.sh

  - name: remove docker images form ansible server
    command: docker rmi capstone:latest adinalini/capstone
    ignore_errors: yes
